/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BaseDatos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author zombozo
 */
public class PantallaProveedores extends javax.swing.JFrame {
proveedores basedatosProveedores;
    /**
     * Creates new form PantallaProveedores
     */
    public PantallaProveedores() {
        initComponents();
        this.basedatosProveedores=new proveedores();
        proveedores.creaDb();
        agregarItems();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoNomProveedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CampoInformacion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        BarraProveedores = new javax.swing.JMenuBar();
        operaciones = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BaseDatos/etiquetas.png"))); // NOI18N
        jLabel1.setText("REGISTRA UN NUEVO PROVEEDOR");

        jLabel3.setText("NOMBRE PROVEEDOR:");

        CampoNomProveedor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setText("INFORMACION:");

        CampoInformacion.setColumns(20);
        CampoInformacion.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        CampoInformacion.setRows(5);
        jScrollPane1.setViewportView(CampoInformacion);

        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BaseDatos/c-yes.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon("C:\\Users\\zombozo\\Desktop\\iconos\\c-yes@0.5x.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        operaciones.setText("Operaciones");
        BarraProveedores.add(operaciones);

        setJMenuBar(BarraProveedores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoNomProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CampoNomProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(13, 126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean estado= this.CampoNomProveedor.getText().isEmpty();
        estado |=this.CampoInformacion.getText().isEmpty();
        if(estado==false){
            this.basedatosProveedores.setNombre_proveedor(this.CampoNomProveedor.getText().toString());
        this.basedatosProveedores.setInfo(this.CampoInformacion.getText().toString());
        boolean estados=this.basedatosProveedores.guardaProveedorDB();
        if(estados){
            JOptionPane.showMessageDialog(rootPane, "se a creado el proveedor", "avizo", WIDTH, null);
            this.CampoInformacion.setText("");
            this.CampoNomProveedor.setText("");
        }else{
            JOptionPane.showMessageDialog(rootPane, "error : no se a creado el proveedor"+"\n"+proveedores.mensaje, "avizo", WIDTH, null);
        }
                
        }else{
            JOptionPane.showMessageDialog(rootPane, " Intentas crear proveedor con campos vacios ", "Error de descuido", WIDTH);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraProveedores;
    private javax.swing.JTextArea CampoInformacion;
    private javax.swing.JTextField CampoNomProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu operaciones;
    // End of variables declaration//GEN-END:variables

   private void agregarItems() {
         ArrayList<JMenuItem> items;
        ItemsMenu obtenerItems=new ItemsMenu();
        items=obtenerItems.items();
        for(int a=0;a<items.size();a++){
            
            int b=a;
            operaciones.add(items.get(a));
            items.get(a).addActionListener(new ActionListener(){
                boolean estados;
                @Override
                public void actionPerformed(ActionEvent e) {
           
                 estados=obtenerItems.metodos(b);
                 if(estados==true){
                    cerrar();
                 }
                }
            });
       }
      
        
    }

   void cerrar(){
        this.dispose();
    }
}
